global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'homelab'

      
rule_files:


scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['mon_node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['mon_cadvisor:8080']
      
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
      
  - job_name: 'mariadb'
    scrape_interval: "15s"
    static_configs:
      - targets: ['mon_db-exporter:9104']
      
  - job_name: redis
    static_configs:
      - targets: ['mon_redis-exporter:9121']
